# Generated by Django 6.1 on 2026-08-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_date_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['user__id'], 'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['status', 'user'], name='users_selle_status_015885_idx'),
        ),
    ]
