# Generated by Django 6.1 on 2026-08-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действие продавца'),
        ),
    ]
