# Generated by Django 6.1 on 2026-08-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_seller_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_first_n_11395a_idx',
        ),
        migrations.RemoveIndex(
            model_name='seller',
            name='users_selle_status_015885_idx',
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['first_name'], name='users_custo_first_n_4c3095_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_birth'], name='users_custo_date_bi_87522e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number'], name='users_custo_phone_n_f2d675_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['status'], name='users_selle_status_e774b4_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['user'], name='users_selle_user_id_9cd2b5_idx'),
        ),
    ]
