# Generated by Django 6.1 on 2026-09-24 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_users_custo_first_n_11395a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(blank=True, max_length=12, null=True)),
                ('snils', models.CharField(blank=True, max_length=14, null=True)),
                ('passport_series', models.CharField(blank=True, max_length=4, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=6, null=True)),
                ('passport_issued_by', models.TextField(blank=True, null=True)),
                ('passport_issued_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Личные документы',
                'verbose_name_plural': 'Личные документы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер контракта')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['-id'], 'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.RemoveIndex(
            model_name='seller',
            name='users_selle_user_id_9cd2b5_idx',
        ),
        migrations.AddField(
            model_name='personaldata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='personaldata',
            index=models.Index(fields=['inn'], name='users_perso_inn_08cdd0_idx'),
        ),
        migrations.AddIndex(
            model_name='personaldata',
            index=models.Index(fields=['snils'], name='users_perso_snils_9436b9_idx'),
        ),
        migrations.AddIndex(
            model_name='personaldata',
            index=models.Index(fields=['passport_series', 'passport_number'], name='users_perso_passpor_960fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['is_active'], name='users_worke_is_acti_574821_idx'),
        ),
    ]
