# Generated by Django 6.1 on 2026-09-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_personaldata_worker_alter_seller_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
                'ordering': ['-id', 'is_active'],
            },
        ),
        migrations.RemoveIndex(
            model_name='worker',
            name='users_worke_is_acti_574821_idx',
        ),
        migrations.AddField(
            model_name='agent',
            name='personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaldata_agent', to='users.personaldata', verbose_name='Данные об агенте'),
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['personal_data'], name='users_agent_persona_ec05ec_idx'),
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
