# Generated by Django 6.1 on 2026-09-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_agent_remove_worker_users_worke_is_acti_574821_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='snils',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='personaldata',
            unique_together={('passport_series', 'passport_number')},
        ),
    ]
