# Generated by Django 6.1 on 2026-09-18 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pickuppoint_order_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Заказ в ПВЗ',
                'verbose_name_plural': 'Заказы в ПВЗ',
            },
        ),
        migrations.CreateModel(
            name='OrderPickupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(max_length=200, verbose_name='Действие')),
                ('time_active', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'История заказов',
            },
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_address_b48f25_idx',
        ),
        migrations.AddField(
            model_name='orderpickup',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pickups', to='orders.order', verbose_name='Ид. заказа'),
        ),
        migrations.AddField(
            model_name='orderpickup',
            name='pickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.pickuppoint', verbose_name='Ид. ПВЗ'),
        ),
        migrations.AddField(
            model_name='orderpickuphistory',
            name='order_pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='orders.orderpickup', verbose_name='Ид. заказа ПВЗ'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddIndex(
            model_name='orderpickup',
            index=models.Index(fields=['pickup', 'order'], name='orders_orde_pickup__9fca2d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpickuphistory',
            index=models.Index(fields=['order_pickup'], name='orders_orde_order_p_c855ea_idx'),
        ),
    ]
