# Generated by Django 6.1 on 2026-09-18 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderpickup_orderpickuphistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpickup',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pickups', to='orders.order', verbose_name='Ид. заказа'),
        ),
    ]
