# Generated by Django 6.1 on 2026-09-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderpickup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('success', 'На ПВЗ'), ('cancelled', 'Отменён'), ('got', 'Получен')], default='pending', max_length=15),
        ),
    ]
