# Generated by Django 6.1 on 2026-09-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderpickup_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderpickup',
            name='orders_orde_pickup__9fca2d_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderpickuphistory',
            name='orders_orde_order_p_c855ea_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('shipped', 'Отправлен'), ('success', 'На ПВЗ'), ('cancelled', 'Отменён'), ('got', 'Получен')], default='pending', max_length=15),
        ),
        migrations.RemoveField(
            model_name='orderpickup',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderpickup',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='orderpickuphistory',
            name='order_pickup',
        ),
        migrations.DeleteModel(
            name='PickupPoint',
        ),
        migrations.DeleteModel(
            name='OrderPickup',
        ),
        migrations.DeleteModel(
            name='OrderPickupHistory',
        ),
    ]
