# Generated by Django 6.1 on 2026-09-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_remove_orderpickup_orders_orde_pickup__9fca2d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ширина')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пункт выдачи заказов',
                'verbose_name_plural': 'Пункты выдачи заказов',
                'db_table': 'orders_pickuppoint',
            },
        ),
        migrations.CreateModel(
            name='OrderPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pickup', to='orders.order', verbose_name='Ид. заказа')),
                ('pickup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pickups.pickuppoint', verbose_name='Ид. ПВЗ')),
            ],
            options={
                'verbose_name': 'Заказ в ПВЗ',
                'verbose_name_plural': 'Заказы в ПВЗ',
                'db_table': 'orders_orderpickup',
            },
        ),
        migrations.CreateModel(
            name='OrderPickupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(max_length=200, verbose_name='Действие')),
                ('time_active', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('order_pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='pickups.orderpickup', verbose_name='Ид. заказа ПВЗ')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'История заказов',
                'db_table': 'orders_orderpickuphistory',
                'indexes': [models.Index(fields=['order_pickup'], name='orders_orde_order_p_c855ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='orderpickup',
            index=models.Index(fields=['pickup', 'order'], name='orders_orde_pickup__9fca2d_idx'),
        ),
    ]
