# Generated by Django 6.1 on 2026-09-20 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderpickup_orders_orde_pickup__9fca2d_idx_and_more'),
        ('pickups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpickup',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pickup', to='orders.order', verbose_name='Ид. заказа'),
        ),
    ]
