# Generated by Django 6.1 on 2026-09-20 15:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0002_alter_orderpickup_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_pickup', to='pickups.pickuppoint', verbose_name='ПВЗ для отзывов')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_user', to=settings.AUTH_USER_MODEL, verbose_name='Отзыв от пользователя')),
            ],
            options={
                'verbose_name': 'Отзыв к ПВЗ',
                'verbose_name_plural': 'Отзывы к ПВЗ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='pickups_pic_user_id_10b60f_idx')],
                'constraints': [models.UniqueConstraint(fields=('pickup', 'user'), name='unique_pickup_user_feedback')],
            },
        ),
        migrations.CreateModel(
            name='PickupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pickups/%Y/%m/%d/', verbose_name='Путь до изображения ПВЗ')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pickups.pickuppoint', verbose_name='Фотографии ПВЗ')),
            ],
            options={
                'verbose_name': 'Изображение ПВЗ',
                'verbose_name_plural': 'Изображения ПВЗ',
                'indexes': [models.Index(fields=['pickup'], name='pickups_pic_pickup__a21903_idx')],
            },
        ),
    ]
