# Generated by Django 6.1 on 2026-09-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0003_pickupfeedback_pickupimage'),
        ('users', '0009_agent_remove_worker_users_worke_is_acti_574821_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_points', to='users.agent', verbose_name='Агент'),
        ),
    ]
