# Generated by Django 5.2.17 on 2026-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0004_pickuppoint_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='address',
            field=models.TextField(blank=True, max_length=400, null=True, unique=True, verbose_name='Адрес ПВЗ'),
        ),
    ]
