# Generated by Django 6.1 on 2026-09-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Остаток товара'),
        ),
    ]
